from __future__ import annotations


LEVEL_LABELS = {
    "da": {"let": "Let", "mellem": "Mellem", "svaer": "Svær", "random": "Blandet"},
    "en": {"let": "Easy", "mellem": "Medium", "svaer": "Hard", "random": "Mixed"},
}


CATEGORY_DA = {
    "plus": "Regning",
    "minus": "Regning",
    "gange": "Regning",
    "division": "Regning",
    "procent": "Regning",
    "broeker": "Regning",
    "visuel_plus": "Visuelle opgaver",
    "visuel_minus": "Visuelle opgaver",
    "visuel_gange": "Visuelle opgaver",
    "visuel_division": "Visuelle opgaver",
    "visuel_division_2": "Visuelle opgaver",
    "visuel_procent": "Visuelle opgaver",
    "visuel_broek": "Visuelle opgaver",
    "visuel_areal": "Visuelle opgaver",
    "areal_firkant": "Geometri",
    "omkreds_firkant": "Geometri",
    "areal_trekant": "Geometri",
    "areal_cirkel": "Geometri",
    "omkreds_cirkel": "Geometri",
    "pytagoras": "Geometri",
    "vinkel_trekant": "Geometri",
    "vinkel_firkant": "Geometri",
    "ligninger": "Algebra og tal",
    "lav_tallet": "Algebra og tal",
    "find_primtal": "Algebra og tal",
    "talpyramide": "Mønstre og logik",
    "gangepyramide": "Mønstre og logik",
    "raekkefoelger": "Mønstre og logik",
    "kode_opgaver": "Mønstre og logik",
    "hemmelige_koder": "Mønstre og logik",
    "rangering_regnestykker": "Mønstre og logik",
    "rutespil": "Mønstre og logik",
    "labyrint_spil": "Mønstre og logik",
    "klokke": "Tid",
    "cykeltid": "Tid",
    "laes_og_forstaa": "Matematiklæsning",
}


CATEGORY_EN = {
    "Regning": "Arithmetic",
    "Visuelle opgaver": "Visual tasks",
    "Geometri": "Geometry",
    "Algebra og tal": "Algebra and numbers",
    "Mønstre og logik": "Patterns and logic",
    "Tid": "Time",
    "Matematiklæsning": "Math reading",
}


TASK_TEXT_EN = {
    "plus": ("Addition", "Calculate each addition problem and write the answer."),
    "visuel_plus": ("Visual addition", "Count the objects and write the answer."),
    "minus": ("Subtraction", "Calculate each subtraction problem and write the answer."),
    "visuel_minus": ("Visual subtraction", "Cross out objects and write how many are left."),
    "gange": ("Multiplication", "Calculate each multiplication problem and write the answer."),
    "visuel_gange": ("Visual multiplication", "Count rows and columns, then write the multiplication."),
    "division": ("Division", "Calculate each division problem and write the answer."),
    "visuel_division": ("Visual division", "Share the objects equally and write the answer."),
    "visuel_division_2": ("Cake sharing", "Share the cakes equally between the people eating."),
    "procent": ("Percent", "Calculate each percent problem and write the answer."),
    "broeker": ("Fractions", "Calculate the fraction problems and write the answer."),
    "visuel_procent": ("Visual percent", "Find what percent of the squares are colored."),
    "visuel_broek": ("Visual fraction", "Write the fraction for the colored part."),
    "visuel_areal": ("Visual area", "Find how many cakes can be made from the dough."),
    "areal_firkant": ("Area of rectangles", "Find the area in each problem."),
    "omkreds_firkant": ("Perimeter of rectangles", "Find the perimeter in each problem."),
    "areal_trekant": ("Area of triangles", "Find the area in each problem."),
    "areal_cirkel": ("Area of circles", "Find the area in each problem."),
    "omkreds_cirkel": ("Circumference of circles", "Find the circumference in each problem."),
    "pytagoras": ("Pythagoras", "Use a^2 + b^2 = c^2 to find the missing side."),
    "cykeltid": ("Cycling time", "Calculate how long the trip takes."),
    "ligninger": ("Equations", "Find x, or find x and y, in each problem."),
    "klokke": ("Clock", "Find the time between the two clock times."),
    "talpyramide": ("Number pyramids", "Add the two lower boxes together."),
    "gangepyramide": ("Multiplication pyramids", "Multiply the two lower boxes together."),
    "lav_tallet": ("Make the number", "Build the number by multiplying prime numbers."),
    "find_primtal": ("Find primes", "Find the prime numbers among the numbers."),
    "rangering_regnestykker": ("Order calculations", "Use estimation. Put the calculations from smallest to largest."),
    "rutespil": ("Route game", "Find three paths down to the correct numbers."),
    "vinkel_trekant": ("Triangle angles", "Find the hidden angle."),
    "vinkel_firkant": ("Quadrilateral angles", "Find the hidden angle."),
    "labyrint_spil": ("Maze game", "Go from START to FINISH through the maze."),
    "raekkefoelger": ("Sequences", "Find the pattern and write the missing term."),
    "kode_opgaver": ("Programming code", "Read the small code from top to bottom and find the final value."),
    "hemmelige_koder": ("Secret codes", "Crack the code and write the hidden message."),
    "laes_og_forstaa": ("Read and understand math", "Read the text. Find the information you need and solve the problem."),
}
